name : Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: set env
    runs-on: ubuntu-latest
    steps:
    - name : CheckOut
      uses : actions/checkout@v2
    - name : set_up_python3.8
      uses : actions/setup-python@v4
      with : 
        python-version : 3.8
        architecture: "x64"
    - name: install poetry
      run: pipx install poetry
      shell: bash
    
    - name : export requirement
      run: poetry export --output requirements.txt
      shell : bash
      
    - name : install dependance
      run: pip install -r requirements.txt
      shell : bash

    - name : InstallDependance
      run: poetry install -E all
      shell: bash

    - name : BuildDist
      run : poetry build
      shell: bash 

    - name: Create Release
      uses: actions/upload-artifact@v3.1.1




  
