name : Release

on:
  push:
    tags:        
      - "v*"


jobs:
  build:
    name: set env
    runs-on: ubuntu-latest
    steps:
    - name : Checkout
      uses : actions/checkout@v2

    - name : set_up_python3.8
      uses : actions/setup-python@v4
      with : 
        python-version : 3.8
        architecture: "x64"
    - name: Install poetry
      run: pipx install poetry
      shell: bash

    - name : Install dependance
      run: poetry install --without dev
      shell: bash

    - name : Build dist
      run : poetry build
      shell: bash 

    # - name: upload artifact
    #   uses: actions/upload-artifact@v3.1.1
    #   with:
    #     tag_name: ${{steps.get_version.outputs.VERSION }}
    #     release_name: ${{steps.get_version.outputs.VERSION }}
    #     name: build_result
    #     path: dist/*

    # - name: Download a Build Artifact
    #   uses: actions/download-artifact@v3.0.1
    #   with:
    #     name: build_result

    # - name : Check pwd
    #   run: pwd
    #   shell: bash
    
    # - name : Show files
    #   run: ls -l
    #   shell: bash
      
    - name : Realease whl
      uses : ncipollo/release-action@main/v1.12.0
      with :
        artifacts: "./dist/*.whl,./dist/*.tar.gz"
        generateReleaseNotes: true
      
    - name : Publish to pypi
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}


  
